FROM node:14-alpine3.14
WORKDIR /home/node/app
COPY package*.json ./
RUN npm install && npm install -g browserify nexe@3.3.7
COPY --from=ayoitson:nexecache /var/nexe/linux-x64-12.16.2 /var/nexe/
COPY . .
RUN npm run build && LINUXBUILD=ayoitson sh make_dist.sh linuxonly

FROM jrottenberg/ffmpeg:4.3-nvidia1804
EXPOSE 8000
WORKDIR /home/node/app
ENTRYPOINT [ "./ayoitson" ]
COPY --from=0 /home/node/app/dist/ayoitson /home/node/app/
RUN ln -s /usr/local/bin/ffmpeg /usr/bin/ffmpeg
