/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Public — no auth required. Suitable for monitoring and k8s probes.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Server is reachable */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Health'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Version info
     * @description Returns Ayoitson, ffmpeg, and node versions. Auth-required because it discloses dependency surface.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Version info */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Version'];
          };
        };
        401: components['responses']['Unauthorized'];
        502: components['responses']['UpstreamError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * First-run setup
     * @description Creates the initial API key. Returns 409 once any active key exists.
     *     Web setup is loopback-only by default; use `scripts/first-run.js` on
     *     the host or deliberately set `AYOITSON_EXPOSE_WEB_SETUP=1` for remote
     *     provisioning.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name?: string;
          };
        };
      };
      responses: {
        /** @description Master key created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreatedKey'];
          };
        };
        403: components['responses']['Forbidden'];
        409: components['responses']['Conflict'];
        503: components['responses']['ServiceUnavailable'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/api-keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List API keys
     * @description Returns key metadata only. Raw keys and hashes are never returned.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API key metadata */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiKeyMetadata'][];
          };
        };
        401: components['responses']['Unauthorized'];
        503: components['responses']['ServiceUnavailable'];
      };
    };
    put?: never;
    /**
     * Create API key
     * @description Creates a new operator/browser key. The raw key is returned once in this response.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiKeyCreate'];
        };
      };
      responses: {
        /** @description API key created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreatedKey'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
        503: components['responses']['ServiceUnavailable'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/api-keys/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke API key */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API key revoke result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiKeyRevokeResult'];
          };
        };
        401: components['responses']['Unauthorized'];
        503: components['responses']['ServiceUnavailable'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/audit-log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read recent audit log entries */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recent audit entries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuditLogResponse'];
          };
        };
        401: components['responses']['Unauthorized'];
        503: components['responses']['ServiceUnavailable'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/backup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download SQLite backup snapshot
     * @description Streams a point-in-time SQLite `.backup` snapshot. Requires a valid
     *     API key with `*`, `admin`, or `admin:backup` scope.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SQLite database backup */
        200: {
          headers: {
            /** @description Attachment filename for the SQLite backup. */
            'Content-Disposition'?: string;
            /** @description Always `no-store`. */
            'Cache-Control'?: string;
            [name: string]: unknown;
          };
          content: {
            'application/vnd.sqlite3': string;
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
        503: components['responses']['ServiceUnavailable'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/channels': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List channels */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Channel summaries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ChannelSummary'][];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    /** Create channel */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ChannelCreate'];
        };
      };
      responses: {
        /** @description Channel created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              number: number;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/channels/numbers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List channel numbers */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sorted channel numbers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ChannelSummary'][];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/channels/{number}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        number: components['parameters']['ChannelNumber'];
      };
      cookie?: never;
    };
    /** Read channel */
    get: {
      parameters: {
        query?: {
          /** @description When `true`, omit the programs array from the response. */
          programless?: 'true' | 'false';
        };
        header?: never;
        path: {
          number: components['parameters']['ChannelNumber'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Channel object */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Channel'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    /** Update channel */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          number: components['parameters']['ChannelNumber'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Channel'];
        };
      };
      responses: {
        /** @description Channel updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              number: number;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    /** Delete channel */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          number: components['parameters']['ChannelNumber'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Channel removed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteAck'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/channels/{number}/programs': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        number: components['parameters']['ChannelNumber'];
      };
      cookie?: never;
    };
    /** Stream channel programs */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          number: components['parameters']['ChannelNumber'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Streamed JSON array of programs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/channels/{number}/description': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        number: components['parameters']['ChannelNumber'];
      };
      cookie?: never;
    };
    /** Channel descriptor */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          number: components['parameters']['ChannelNumber'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Minimal channel descriptor */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ChannelDescription'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/plex-servers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Plex servers
     * @description Auth-required because the response discloses server identity / URL even with tokens redacted.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plex server list (tokens redacted) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlexServerPublic'][];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    /** Create Plex server */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PlexServerCreate'];
        };
      };
      responses: {
        /** @description Plex server created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              created?: boolean;
              name?: string;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/plex-servers/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components['parameters']['PlexServerName'];
      };
      cookie?: never;
    };
    get?: never;
    /** Update Plex server */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components['parameters']['PlexServerName'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PlexServerCreate'];
        };
      };
      responses: {
        /** @description Plex server updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlexServerUpdateResult'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    /** Delete Plex server */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components['parameters']['PlexServerName'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plex server deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteAck'];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/plex-servers/{name}/status-check': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components['parameters']['PlexServerName'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Probe a configured Plex server */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: components['parameters']['PlexServerName'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Probe result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlexStatus'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/plex-servers/foreign-status-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Probe an arbitrary Plex server (body) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PlexServerCreate'];
        };
      };
      responses: {
        /** @description Probe result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlexStatus'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/plex-servers/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Legacy Plex status helper
     * @deprecated
     * @description Legacy compatibility route. Prefer `POST /api/plex-servers/{name}/status-check`.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name?: string;
          };
        };
      };
      responses: {
        /** @description Probe result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlexStatus'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/filler-lists': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List filler lists */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Filler list summaries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    /** Create filler list */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Filler list created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: string;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/filler-lists/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    /** Read filler list */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Filler list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    /** Update filler list */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Filler list updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              updated?: boolean;
              id?: string;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    /** Delete filler list */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Filler list deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteAck'];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/filler-lists/{id}/channels': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    /** Channels using this filler list */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Channel list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/custom-shows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List custom shows */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Custom show summaries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            }[];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    /** Create custom show */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Custom show created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: string;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/custom-shows/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    /** Read custom show */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Custom show */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    /** Update custom show */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Custom show updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              updated?: boolean;
              id?: string;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    /** Delete custom show */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['ResourceId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Custom show deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteAck'];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/ffmpeg': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read FFmpeg settings */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description FFmpeg settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    /** Update FFmpeg settings */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Updated FFmpeg settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/ffmpeg/known-paths': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List detected well-known FFmpeg paths */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Absolute FFmpeg paths detected on this host */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              paths: string[];
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/ffmpeg/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset FFmpeg settings to defaults */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reset FFmpeg settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/plex': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Plex settings */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plex settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    /** Update Plex settings */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Updated Plex settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/plex/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset Plex settings to defaults */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reset Plex settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/xmltv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read XMLTV settings
     * @description Note — the XMLTV file path is hard-coded server-side at `${DATABASE}/xmltv.xml`.
     *     The `file` field is intentionally omitted from request and response shapes.
     *     This closes F10-xmltv-readfile (operator-controllable arbitrary-file-read).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description XMLTV settings (no `file` field) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['XmltvSettings'];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    /**
     * Update XMLTV settings
     * @description Bodies containing a `file` field are rejected with 400.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['XmltvSettings'];
        };
      };
      responses: {
        /** @description Updated XMLTV settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['XmltvSettings'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/xmltv/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset XMLTV settings to defaults */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reset XMLTV settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['XmltvSettings'];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/hdhr': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read HDHR settings */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description HDHR settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    /** Update HDHR settings */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Updated HDHR settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/hdhr/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset HDHR settings to defaults */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reset HDHR settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** TV guide status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Guide status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/debug': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Full guide dump (admin) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Full guide */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/last-refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Last refresh epoch ms */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Last refresh time */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              value?: number;
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/channels/{number}': {
    parameters: {
      query: {
        dateFrom: string;
        dateTo: string;
      };
      header?: never;
      path: {
        number: components['parameters']['ChannelNumber'];
      };
      cookie?: never;
    };
    /** Channel guide lineup */
    get: {
      parameters: {
        query: {
          dateFrom: string;
          dateTo: string;
        };
        header?: never;
        path: {
          number: components['parameters']['ChannelNumber'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Lineup */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/xmltv.xml': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Serve xmltv.xml */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description XMLTV XML payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/xml': string;
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/channels.m3u': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Serve channels.m3u */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description M3U text payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string;
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/time-slots': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Time-slot tool */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            programs: {
              [key: string]: unknown;
            }[];
            schedule: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Streamed time-slot result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/guide/random-slots': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Random-slot tool */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            programs: {
              [key: string]: unknown;
            }[];
            schedule: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Streamed random-slot result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/uploads/image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload an image
     * @description Multipart form-data. File ≤ 10 MiB. Mime types accepted: image/png,
     *     image/jpeg, image/gif, image/webp. Filename is sanitized; the on-disk
     *     name is `{uuid}.{extension}` and the original filename is returned
     *     only as metadata.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /** Format: binary */
            image: string;
          };
        };
      };
      responses: {
        /** @description Image stored */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UploadResult'];
          };
        };
        400: components['responses']['ValidationError'];
        401: components['responses']['Unauthorized'];
        413: components['responses']['PayloadTooLarge'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @enum {string} */
      code:
        | 'VALIDATION_ERROR'
        | 'UNAUTHORIZED'
        | 'FORBIDDEN'
        | 'NOT_FOUND'
        | 'CONFLICT'
        | 'PAYLOAD_TOO_LARGE'
        | 'RATE_LIMITED'
        | 'INTERNAL'
        | 'UPSTREAM_ERROR'
        | 'SERVICE_UNAVAILABLE';
      message: string;
      details?: {
        [key: string]: unknown;
      };
    };
    Health: {
      /** @enum {string} */
      status: 'ok';
      version?: string;
      /** @description Process uptime in seconds */
      uptime?: number;
    };
    Version: {
      name?: string;
      version?: string;
      ffmpeg?: string;
      nodejs?: string;
    };
    CreatedKey: {
      metadata: components['schemas']['ApiKeyMetadata'];
      /** @description Raw API key value. Shown ONCE; never reissued. */
      rawKey: string;
    };
    ApiKeyMetadata: {
      id: string;
      name: string;
      scopes: string[];
      createdAt: string;
      lastUsedAt: string | null;
      revokedAt: string | null;
    };
    ApiKeyCreate: {
      name: string;
    };
    ApiKeyRevokeResult: {
      revoked: boolean;
    };
    AuditEntry: {
      /** Format: date-time */
      ts: string;
      event: string;
      actor?: {
        [key: string]: unknown;
      };
      ip?: string;
      userAgent?: string;
      method?: string;
      path?: string;
      detail?: {
        [key: string]: unknown;
      };
    } & {
      [key: string]: unknown;
    };
    AuditLogResponse: {
      path: string;
      entries: components['schemas']['AuditEntry'][];
    };
    ChannelSummary: {
      number?: number;
    };
    Channel: {
      number?: number;
      name?: string;
      icon?: string;
      stealth?: boolean;
      programs?: {
        [key: string]: unknown;
      }[];
      fallback?: {
        [key: string]: unknown;
      }[];
    } & {
      [key: string]: unknown;
    };
    ChannelCreate: components['schemas']['Channel'] & Record<string, never>;
    ChannelDescription: {
      number: number;
      icon?: string;
      name?: string;
      stealth?: boolean;
    };
    PlexServerPublic: {
      name: string;
      uri?: string;
      index?: number;
      arGuide?: boolean;
      arChannels?: boolean;
    };
    PlexServerCreate: {
      name: string;
      uri: string;
      accessToken: string;
      arGuide?: boolean;
      arChannels?: boolean;
    };
    PlexServerUpdateResult: {
      updated?: boolean;
      name?: string;
      modifiedPrograms?: number;
      destroyedPrograms?: number;
    };
    PlexStatus: {
      status?: number;
    };
    XmltvSettings: {
      _id?: string;
      cache?: number;
      refresh?: number;
      enableImageCache?: boolean;
    };
    DeleteAck: {
      deleted?: boolean;
      id?: string;
      number?: number;
      name?: string;
    };
    UploadResult: {
      status?: boolean;
      message?: string;
      data?: {
        name?: string;
        originalName?: string;
        mimetype?: string;
        size?: number;
        fileUrl?: string;
      };
    };
  };
  responses: {
    /** @description Missing or invalid X-API-Key */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Valid key, insufficient scope */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource exists or version mismatch */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Request body or parameter is invalid */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Body exceeds size limit */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Upstream dependency failed */
    UpstreamError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Server starting up or shutting down */
    ServiceUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    ChannelNumber: number;
    PlexServerName: string;
    ResourceId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
